# Site settings
title: Static C3
email: davclark@berkeley.edu
description: > 
  A simple site to put a JS visulization somewhere.
baseurl: "/static-c3" # the subpath of your site, e.g. /blog/
url: "http://glass-bead-labs.github.io/static-c3"
twitter_username: GlassBeadLabs
github_username: glass-bead-labs

# Build settings
markdown: kramdown
